import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { getStrategiesRegistry, getStrategyVersionDetail } from "../api";
import Strategies from "./Strategies";

vi.mock("../api", () => ({
  getStrategiesRegistry: vi.fn(),
  getStrategyVersionDetail: vi.fn(),
}));

beforeEach(() => {
  vi.clearAllMocks();
  getStrategiesRegistry.mockResolvedValue({
    summary: {
      phase: "13A",
      family_count: 2,
      version_count: 2,
      gate_policy_count: 1,
      benchmark_family: "default_strategy",
    },
    gate_policies: [
      {
        id: 1,
        policy_key: "promotion_gate_policy_v1",
        label: "Promotion Gate Policy v1",
        status: "active",
        policy_json: {
          required_inputs: ["minimum_live_sample_size", "acceptable_drawdown"],
        },
        updated_at: "2026-04-21T08:00:00Z",
      },
    ],
    families: [
      {
        id: 1,
        family: "default_strategy",
        label: "Default Strategy",
        posture: "benchmark_only",
        configured: true,
        review_enabled: true,
        primary_surface: "paper_trading",
        description: "Frozen benchmark truth anchor.",
        disabled_reason: null,
        family_kind: "strategy",
        seeded_from: "builtin",
        updated_at: "2026-04-21T08:00:00Z",
        current_version: {
          id: 1,
          version_key: "default_strategy_benchmark_v1",
          version_label: "Frozen Benchmark v1",
          strategy_name: "prove_the_edge_default",
          version_status: "benchmark",
          autonomy_tier: "shadow_only",
          is_current: true,
          is_frozen: true,
          config_json: {},
          risk_budget_policy: {
            capital: { outstanding_notional_usd: 1000 },
            capacity: { max_open_orders: 12 },
          },
          risk_budget_status: {
            current_outstanding_usd: 0,
            effective_outstanding_cap_usd: 1000,
            regime_label: "thin_liquidity",
            capacity_status: "narrowed",
            risk_of_ruin_label: "normal",
          },
          provenance_json: {},
          latest_promotion_evaluation: {
            id: 11,
            family_id: 1,
            strategy_version_id: 1,
            gate_policy_id: 1,
            evaluation_kind: "pilot_readiness_gate",
            evaluation_status: "observe",
            autonomy_tier: "assisted_live",
          },
          evidence_alignment: {
            surface_status: "partial",
            surfaces_present: 1,
            surface_keys_present: ["scorecard"],
            latest_surface_at: "2026-04-21T00:00:00Z",
            latest_promotion_evaluation: {
              id: 11,
              family_id: 1,
              strategy_version_id: 1,
              gate_policy_id: 1,
              evaluation_kind: "pilot_readiness_gate",
              evaluation_status: "observe",
              autonomy_tier: "assisted_live",
            },
            latest_replay_run: null,
            live_shadow: null,
            latest_scorecard: {
              id: 101,
              status: "watch",
              window_start: "2026-04-20T00:00:00Z",
              window_end: "2026-04-21T00:00:00Z",
              live_orders_count: 0,
              fills_count: 0,
              incident_count: 0,
              net_pnl: "2.50",
              avg_shadow_gap_bps: "1.50",
              coverage_limited_count: 0,
              created_at: "2026-04-21T08:00:00Z",
            },
            latest_readiness_report: null,
          },
          evidence_counts: {
            strategy_runs: 2,
            paper_trades: 4,
            replay_runs: 0,
            live_orders: 0,
            pilot_scorecards: 0,
            readiness_reports: 0,
          },
          updated_at: "2026-04-21T08:00:00Z",
        },
        versions: [
          {
            id: 1,
            version_key: "default_strategy_benchmark_v1",
            version_label: "Frozen Benchmark v1",
            strategy_name: "prove_the_edge_default",
            version_status: "benchmark",
            autonomy_tier: "shadow_only",
            is_current: true,
            is_frozen: true,
            config_json: {},
            risk_budget_policy: {
              capital: { outstanding_notional_usd: 1000 },
              capacity: { max_open_orders: 12 },
            },
            risk_budget_status: {
              current_outstanding_usd: 0,
              effective_outstanding_cap_usd: 1000,
              regime_label: "thin_liquidity",
              capacity_status: "narrowed",
              risk_of_ruin_label: "normal",
            },
            provenance_json: {},
            latest_promotion_evaluation: {
              id: 11,
              family_id: 1,
              strategy_version_id: 1,
              gate_policy_id: 1,
              evaluation_kind: "pilot_readiness_gate",
              evaluation_status: "observe",
              autonomy_tier: "assisted_live",
            },
            evidence_alignment: {
              surface_status: "partial",
              surfaces_present: 1,
              surface_keys_present: ["scorecard"],
              latest_surface_at: "2026-04-21T00:00:00Z",
              latest_promotion_evaluation: {
                id: 11,
                family_id: 1,
                strategy_version_id: 1,
                gate_policy_id: 1,
                evaluation_kind: "pilot_readiness_gate",
                evaluation_status: "observe",
                autonomy_tier: "assisted_live",
              },
              latest_replay_run: null,
              live_shadow: null,
              latest_scorecard: {
                id: 101,
                status: "watch",
                window_start: "2026-04-20T00:00:00Z",
                window_end: "2026-04-21T00:00:00Z",
                live_orders_count: 0,
                fills_count: 0,
                incident_count: 0,
                net_pnl: "2.50",
                avg_shadow_gap_bps: "1.50",
                coverage_limited_count: 0,
                created_at: "2026-04-21T08:00:00Z",
              },
              latest_readiness_report: null,
            },
            evidence_counts: {
              strategy_runs: 2,
              paper_trades: 4,
              replay_runs: 0,
              live_orders: 0,
              pilot_scorecards: 0,
              readiness_reports: 0,
            },
            updated_at: "2026-04-21T08:00:00Z",
          },
        ],
        latest_promotion_evaluation: {
          id: 11,
          family_id: 1,
          strategy_version_id: 1,
          gate_policy_id: 1,
          evaluation_kind: "pilot_readiness_gate",
          evaluation_status: "observe",
          autonomy_tier: "assisted_live",
          evaluation_window_start: "2026-04-20T00:00:00Z",
          evaluation_window_end: "2026-04-21T00:00:00Z",
          provenance_json: {
            promotion_gate_policy_key: "promotion_gate_policy_v1",
            config_hash: "cfg-default-1234",
            market_universe_hash: "mkt-default-5678",
          },
          summary_json: {
            readiness_status: "manual_only",
            readiness_blockers: [],
            incident_count: 0,
            approval_backlog_count: 0,
          },
          created_at: "2026-04-21T08:00:00Z",
          updated_at: "2026-04-21T08:00:00Z",
        },
        latest_demotion_event: null,
      },
      {
        id: 2,
        family: "exec_policy",
        label: "Execution Policy",
        posture: "advisory_only",
        configured: true,
        review_enabled: true,
        primary_surface: "pilot_console",
        description: "Shared execution infrastructure.",
        disabled_reason: null,
        family_kind: "infrastructure",
        seeded_from: "builtin",
        updated_at: "2026-04-21T08:00:00Z",
        current_version: {
          id: 2,
          version_key: "exec_policy_infra_v1",
          version_label: "Execution Policy Infra v1",
          strategy_name: null,
          version_status: "promoted",
          autonomy_tier: "assisted_live",
          is_current: true,
          is_frozen: false,
          config_json: {},
          risk_budget_policy: {
            capital: { outstanding_notional_usd: 75 },
            capacity: { max_open_orders: 5 },
          },
          risk_budget_status: {
            current_outstanding_usd: 25,
            effective_outstanding_cap_usd: 75,
            effective_capacity_ceiling_usd: 50,
            effective_max_order_notional_usd: 25,
            open_order_count: 2,
            effective_max_open_orders: 5,
            regime_label: "thin_liquidity",
            capacity_status: "constrained",
            risk_of_ruin_label: "warning",
            risk_of_ruin_score: 0.62,
          },
          provenance_json: {},
          latest_promotion_evaluation: {
            id: 12,
            family_id: 2,
            strategy_version_id: 2,
            gate_policy_id: 1,
            evaluation_kind: "replay_gate",
            evaluation_status: "observe",
            autonomy_tier: "shadow_only",
          },
          evidence_alignment: {
            surface_status: "complete",
            surfaces_present: 4,
            surface_keys_present: ["replay", "live_shadow", "scorecard", "readiness"],
            latest_surface_at: "2026-04-21T08:15:00Z",
            latest_promotion_evaluation: {
              id: 12,
              family_id: 2,
              strategy_version_id: 2,
              gate_policy_id: 1,
              evaluation_kind: "replay_gate",
              evaluation_status: "observe",
              autonomy_tier: "shadow_only",
            },
            latest_replay_run: {
              id: "run-2",
              run_key: "phase11-exec-1234",
              run_type: "policy_compare",
              reason: "manual",
              status: "completed",
              scenario_count: 3,
              strategy_version_id: 2,
              strategy_version_key: "exec_policy_infra_v1",
              strategy_version_label: "Execution Policy Infra v1",
              time_window_start: "2026-04-20T00:00:00Z",
              time_window_end: "2026-04-21T00:00:00Z",
              started_at: "2026-04-21T07:30:00Z",
              completed_at: "2026-04-21T07:45:00Z",
              promotion_evaluation: {
                id: 12,
                family_id: 2,
                strategy_version_id: 2,
                gate_policy_id: 1,
                evaluation_kind: "replay_gate",
                evaluation_status: "observe",
                autonomy_tier: "shadow_only",
              },
            },
            live_shadow: {
              latest_updated_at: "2026-04-21T08:15:00Z",
              latest_variant_name: "exec_policy",
              latest_reason_code: "replay_matched",
              latest_gap_bps: "4.20",
              latest_realized_net_bps: "11.80",
              latest_replay_run_id: "run-2",
              recent_count_24h: 3,
              coverage_limited_count_24h: 0,
              average_gap_bps_24h: "4.20",
              worst_gap_bps_24h: "6.30",
              breach_count_24h: 1,
            },
            latest_scorecard: {
              id: 201,
              status: "watch",
              window_start: "2026-04-20T00:00:00Z",
              window_end: "2026-04-21T00:00:00Z",
              live_orders_count: 3,
              fills_count: 2,
              incident_count: 1,
              net_pnl: "12.50",
              avg_shadow_gap_bps: "4.20",
              coverage_limited_count: 0,
              created_at: "2026-04-21T08:00:00Z",
            },
            latest_readiness_report: {
              id: 301,
              status: "manual_only",
              window_start: "2026-04-20T00:00:00Z",
              window_end: "2026-04-21T00:00:00Z",
              generated_at: "2026-04-21T08:10:00Z",
              approval_backlog_count: 1,
              coverage_limited_count: 0,
              shadow_gap_breach_count: 1,
              open_incidents: 1,
            },
          },
          evidence_counts: {
            strategy_runs: 0,
            paper_trades: 0,
            replay_runs: 1,
            live_orders: 3,
            pilot_scorecards: 2,
            readiness_reports: 1,
          },
          updated_at: "2026-04-21T08:00:00Z",
        },
        versions: [
          {
            id: 2,
            version_key: "exec_policy_infra_v1",
            version_label: "Execution Policy Infra v1",
            strategy_name: null,
            version_status: "promoted",
            autonomy_tier: "assisted_live",
            is_current: true,
            is_frozen: false,
            config_json: {},
            risk_budget_policy: {
              capital: { outstanding_notional_usd: 75 },
              capacity: { max_open_orders: 5 },
            },
            risk_budget_status: {
              current_outstanding_usd: 25,
              effective_outstanding_cap_usd: 75,
              effective_capacity_ceiling_usd: 50,
              effective_max_order_notional_usd: 25,
              open_order_count: 2,
              effective_max_open_orders: 5,
              regime_label: "thin_liquidity",
              capacity_status: "constrained",
              risk_of_ruin_label: "warning",
              risk_of_ruin_score: 0.62,
            },
            provenance_json: {},
            latest_promotion_evaluation: {
              id: 12,
              family_id: 2,
              strategy_version_id: 2,
              gate_policy_id: 1,
              evaluation_kind: "replay_gate",
              evaluation_status: "observe",
              autonomy_tier: "shadow_only",
            },
            evidence_alignment: {
              surface_status: "complete",
              surfaces_present: 4,
              surface_keys_present: ["replay", "live_shadow", "scorecard", "readiness"],
              latest_surface_at: "2026-04-21T08:15:00Z",
              latest_promotion_evaluation: {
                id: 12,
                family_id: 2,
                strategy_version_id: 2,
                gate_policy_id: 1,
                evaluation_kind: "replay_gate",
                evaluation_status: "observe",
                autonomy_tier: "shadow_only",
              },
              latest_replay_run: {
                id: "run-2",
                run_key: "phase11-exec-1234",
                run_type: "policy_compare",
                reason: "manual",
                status: "completed",
                scenario_count: 3,
                strategy_version_id: 2,
                strategy_version_key: "exec_policy_infra_v1",
                strategy_version_label: "Execution Policy Infra v1",
                time_window_start: "2026-04-20T00:00:00Z",
                time_window_end: "2026-04-21T00:00:00Z",
                started_at: "2026-04-21T07:30:00Z",
                completed_at: "2026-04-21T07:45:00Z",
                promotion_evaluation: {
                  id: 12,
                  family_id: 2,
                  strategy_version_id: 2,
                  gate_policy_id: 1,
                  evaluation_kind: "replay_gate",
                  evaluation_status: "observe",
                  autonomy_tier: "shadow_only",
                },
              },
              live_shadow: {
                latest_updated_at: "2026-04-21T08:15:00Z",
                latest_variant_name: "exec_policy",
                latest_reason_code: "replay_matched",
                latest_gap_bps: "4.20",
                latest_realized_net_bps: "11.80",
                latest_replay_run_id: "run-2",
                recent_count_24h: 3,
                coverage_limited_count_24h: 0,
                average_gap_bps_24h: "4.20",
                worst_gap_bps_24h: "6.30",
                breach_count_24h: 1,
              },
              latest_scorecard: {
                id: 201,
                status: "watch",
                window_start: "2026-04-20T00:00:00Z",
                window_end: "2026-04-21T00:00:00Z",
                live_orders_count: 3,
                fills_count: 2,
                incident_count: 1,
                net_pnl: "12.50",
                avg_shadow_gap_bps: "4.20",
                coverage_limited_count: 0,
                created_at: "2026-04-21T08:00:00Z",
              },
              latest_readiness_report: {
                id: 301,
                status: "manual_only",
                window_start: "2026-04-20T00:00:00Z",
                window_end: "2026-04-21T00:00:00Z",
                generated_at: "2026-04-21T08:10:00Z",
                approval_backlog_count: 1,
                coverage_limited_count: 0,
                shadow_gap_breach_count: 1,
                open_incidents: 1,
              },
            },
            evidence_counts: {
              strategy_runs: 0,
              paper_trades: 0,
              replay_runs: 1,
              live_orders: 3,
              pilot_scorecards: 2,
              readiness_reports: 1,
            },
            updated_at: "2026-04-21T08:00:00Z",
          },
        ],
        latest_promotion_evaluation: {
          id: 12,
          family_id: 2,
          strategy_version_id: 2,
          gate_policy_id: 1,
          evaluation_kind: "replay_gate",
          evaluation_status: "observe",
          autonomy_tier: "shadow_only",
          evaluation_window_start: "2026-04-20T00:00:00Z",
          evaluation_window_end: "2026-04-21T00:00:00Z",
          provenance_json: {
            promotion_gate_policy_key: "promotion_gate_policy_v1",
            config_hash: "cfg-exec-1234",
            market_universe_hash: "mkt-exec-5678",
            replay_run_key: "phase11-exec-1234",
          },
          summary_json: {
            replay_status: "completed",
            variant_count: 3,
            primary_variant: "exec_policy",
            primary_variant_net_pnl: 12.5,
            coverage_limited_scenarios: 0,
          },
          created_at: "2026-04-21T08:00:00Z",
          updated_at: "2026-04-21T08:00:00Z",
        },
        latest_demotion_event: null,
      },
    ],
    generated_at: "2026-04-21T08:00:00Z",
  });
  getStrategyVersionDetail.mockResolvedValue({
    family: {
      id: 2,
      family: "exec_policy",
      label: "Execution Policy",
      posture: "advisory_only",
      primary_surface: "pilot_console",
      family_kind: "infrastructure",
      description: "Shared execution infrastructure.",
      disabled_reason: null,
      seeded_from: "builtin",
      created_at: "2026-04-21T08:00:00Z",
      updated_at: "2026-04-21T08:00:00Z",
    },
    version: {
      id: 2,
      version_key: "exec_policy_infra_v1",
      version_label: "Execution Policy Infra v1",
      strategy_name: null,
      version_status: "promoted",
      autonomy_tier: "assisted_live",
      is_current: true,
      is_frozen: false,
      config_json: {},
      risk_budget_policy: {
        capital: { outstanding_notional_usd: 75 },
        capacity: { max_open_orders: 5 },
      },
      risk_budget_status: {
        current_outstanding_usd: 25,
        effective_outstanding_cap_usd: 75,
        effective_capacity_ceiling_usd: 50,
        effective_max_order_notional_usd: 25,
        open_order_count: 2,
        effective_max_open_orders: 5,
        regime_label: "thin_liquidity",
        capacity_status: "constrained",
        risk_of_ruin_label: "warning",
        risk_of_ruin_score: 0.62,
      },
      provenance_json: {},
      latest_promotion_evaluation: {
        id: 12,
        family_id: 2,
        strategy_version_id: 2,
        gate_policy_id: 1,
        evaluation_kind: "replay_gate",
        evaluation_status: "observe",
        autonomy_tier: "shadow_only",
      },
      evidence_alignment: {
        surface_status: "complete",
        surfaces_present: 4,
        surface_keys_present: ["replay", "live_shadow", "scorecard", "readiness"],
        latest_surface_at: "2026-04-21T08:15:00Z",
      },
      evidence_counts: {
        strategy_runs: 0,
        paper_trades: 0,
        replay_runs: 1,
        live_orders: 3,
        pilot_scorecards: 2,
        readiness_reports: 1,
      },
      created_at: "2026-04-21T08:00:00Z",
      updated_at: "2026-04-21T08:00:00Z",
    },
    latest_demotion_event: null,
    replay_runs: [
      {
        id: "run-2",
        run_key: "phase11-exec-1234",
        run_type: "policy_compare",
        reason: "manual",
        status: "completed",
        scenario_count: 3,
        strategy_version_id: 2,
        strategy_version_key: "exec_policy_infra_v1",
        strategy_version_label: "Execution Policy Infra v1",
        time_window_start: "2026-04-20T00:00:00Z",
        time_window_end: "2026-04-21T00:00:00Z",
        started_at: "2026-04-21T07:30:00Z",
        completed_at: "2026-04-21T07:45:00Z",
        promotion_evaluation: {
          id: 12,
          family_id: 2,
          strategy_version_id: 2,
          gate_policy_id: 1,
          evaluation_kind: "replay_gate",
          evaluation_status: "observe",
          autonomy_tier: "shadow_only",
        },
      },
    ],
    live_shadow_evaluations: [
      {
        id: 401,
        live_order_id: "order-1",
        client_order_id: "client-1",
        condition_id: "cond-1",
        asset_id: "asset-1",
        side: "BUY",
        live_order_status: "matched",
        variant_name: "exec_policy",
        gap_bps: "4.20",
        realized_net_bps: "11.80",
        expected_net_ev_bps: "16.00",
        coverage_limited: false,
        reason_code: "replay_matched",
        replay_run_id: "run-2",
        details_json: {},
        created_at: "2026-04-21T08:00:00Z",
        updated_at: "2026-04-21T08:15:00Z",
      },
    ],
    scorecards: [
      {
        id: 201,
        status: "watch",
        window_start: "2026-04-20T00:00:00Z",
        window_end: "2026-04-21T00:00:00Z",
        live_orders_count: 3,
        fills_count: 2,
        incident_count: 1,
        net_pnl: "12.50",
        avg_shadow_gap_bps: "4.20",
        coverage_limited_count: 0,
        created_at: "2026-04-21T08:00:00Z",
      },
    ],
    readiness_reports: [
      {
        id: 301,
        status: "manual_only",
        window_start: "2026-04-20T00:00:00Z",
        window_end: "2026-04-21T00:00:00Z",
        generated_at: "2026-04-21T08:10:00Z",
        approval_backlog_count: 1,
        coverage_limited_count: 0,
        shadow_gap_breach_count: 1,
        open_incidents: 1,
      },
    ],
    promotion_evaluations: [
      {
        id: 12,
        family_id: 2,
        strategy_version_id: 2,
        gate_policy_id: 1,
        evaluation_kind: "replay_gate",
        evaluation_status: "observe",
        autonomy_tier: "shadow_only",
        created_at: "2026-04-21T08:00:00Z",
        updated_at: "2026-04-21T08:00:00Z",
      },
    ],
    gate_history: [
      {
        id: 16,
        family_id: 2,
        strategy_version_id: 2,
        gate_policy_id: 1,
        evaluation_kind: "capital_budget_gate",
        evaluation_status: "constrained",
        autonomy_tier: "shadow_only",
        evaluation_window_start: "2026-04-21T08:10:00Z",
        evaluation_window_end: "2026-04-21T08:16:00Z",
        summary_json: {
          capacity_status: "constrained",
          regime_label: "thin_liquidity",
          reason_codes: ["capacity_ceiling_exceeded"],
        },
        created_at: "2026-04-21T08:16:00Z",
        updated_at: "2026-04-21T08:16:00Z",
      },
      {
        id: 15,
        family_id: 2,
        strategy_version_id: 2,
        gate_policy_id: 1,
        evaluation_kind: "incident_gate",
        evaluation_status: "blocked",
        autonomy_tier: "shadow_only",
        evaluation_window_start: "2026-04-20T08:15:00Z",
        evaluation_window_end: "2026-04-21T08:15:00Z",
        summary_json: {
          incident_count_24h: 1,
          latest_incident_type: "submission_blocked",
        },
        created_at: "2026-04-21T08:15:00Z",
        updated_at: "2026-04-21T08:15:00Z",
      },
      {
        id: 14,
        family_id: 2,
        strategy_version_id: 2,
        gate_policy_id: 1,
        evaluation_kind: "scorecard_gate",
        evaluation_status: "observe",
        autonomy_tier: "assisted_live",
        evaluation_window_start: "2026-04-20T00:00:00Z",
        evaluation_window_end: "2026-04-21T00:00:00Z",
        summary_json: {
          scorecard_status: "watch",
          net_pnl: "12.50",
          incident_count: 1,
        },
        created_at: "2026-04-21T08:05:00Z",
        updated_at: "2026-04-21T08:05:00Z",
      },
      {
        id: 12,
        family_id: 2,
        strategy_version_id: 2,
        gate_policy_id: 1,
        evaluation_kind: "replay_gate",
        evaluation_status: "observe",
        autonomy_tier: "shadow_only",
        evaluation_window_start: "2026-04-20T00:00:00Z",
        evaluation_window_end: "2026-04-21T00:00:00Z",
        summary_json: {
          replay_status: "completed",
          variant_count: 3,
        },
        created_at: "2026-04-21T08:00:00Z",
        updated_at: "2026-04-21T08:00:00Z",
      },
    ],
    demotion_events: [
      {
        id: 1,
        reason_code: "family_cap_exceeded",
        fallback_autonomy_tier: "shadow_only",
        cooling_off_ends_at: "2026-04-22T08:16:00Z",
        observed_at_local: "2026-04-21T08:16:00Z",
      },
    ],
    generated_at: "2026-04-21T08:16:00Z",
  });
});

describe("Strategies", () => {
  test("renders the phase 13 lifecycle registry surface", async () => {
    render(
      <MemoryRouter>
        <Strategies />
      </MemoryRouter>
    );

    expect(await screen.findByText("Strategies")).toBeInTheDocument();
    expect(screen.getAllByText("Frozen Benchmark v1").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Execution Policy Infra v1").length).toBeGreaterThan(0);
    expect(screen.getByText("Promotion Gate Policy v1")).toBeInTheDocument();
    expect(screen.getAllByText("Version State").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Registry Tier").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Latest Gate Verdict").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Recommended Registry Tier").length).toBeGreaterThan(0);
    expect(screen.getByText("cfg-exec-1234")).toBeInTheDocument();
    expect(screen.getAllByText("Replay Gate").length).toBeGreaterThan(0);
    expect(screen.getByText("3 variants")).toBeInTheDocument();
    expect(screen.getAllByText("Evidence Alignment").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Gate / Autonomy").length).toBeGreaterThan(0);
    expect(screen.getByText("3 recent evals")).toBeInTheDocument();
    expect(screen.getByText("4 linked surfaces")).toBeInTheDocument();
    expect(screen.getAllByText("Manual Only").length).toBeGreaterThan(0);
    expect(screen.getByText("Benchmark Health")).toBeInTheDocument();
    expect(screen.getByText("Pilot Console")).toBeInTheDocument();
    expect(screen.getByText("Constrained")).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Inspect Execution Policy Infra v1" }));
    await waitFor(() => {
      expect(getStrategyVersionDetail).toHaveBeenCalledWith(2);
    });
    expect(await screen.findByText("Version Detail")).toBeInTheDocument();
    expect(screen.getByText("Gate History")).toBeInTheDocument();
    expect(screen.getByText("Budget Status")).toBeInTheDocument();
    expect(screen.getByText("Budget Regime")).toBeInTheDocument();
    expect(screen.getByText("Capital Budget Gate")).toBeInTheDocument();
    expect(screen.getByText(/Constrained \| Regime Thin Liquidity \| capacity_ceiling_exceeded/)).toBeInTheDocument();
    expect(screen.getByText("Family Cap Exceeded")).toBeInTheDocument();
    expect(screen.queryByText("No replay runs linked to this version yet.")).not.toBeInTheDocument();
    expect(screen.getAllByText("phase11-exec-1234").length).toBeGreaterThan(0);
    expect(screen.getByText("client-1")).toBeInTheDocument();
    expect(screen.getByText(/Submission Blocked/)).toBeInTheDocument();
  });
});
